### ISSUE TITLE
QR scan to request credential

### ISSUE THREAD

**Issue by kimdhamilton** [digitalcredentials/cred-wallet#52]
## Goal
This tracks a very basic implementation of QR scanning to request a credential for demo purposes only. The standards for credential requests are still WIP; however, we can put together a basic demo of the key pieces from a UX perspective.

## Flow
The [DCC playground](https://digitalcredentials.github.io/playground) has a request screen displaying a QR code. The demo "request credential" workflow will look like this:
- User opens DCC wallet
- Navigates to "Request Credential" screen
- Scan QR code
- Next screen displays:
    - The scanned info. For now, that's just the URL for the "request credential" REST service. Later it might contain other info such as a challenge/nonce
    - A DID auto-populated from the wallet. For now, just make it did:example:123 or something. 
- User hits "submit" button which hits the rest endpoint and returns a signed mock credential

## Details

The CURL request should look like this:
```
curl --header "Content-Type: application/json" --request POST --data '{"subjectDid": "did:example:123"}' https://sign-and-verify.herokuapp.com/request/credentials
```

Note that the request/credentials endpoint is expecting (for now) a simple json object with the subject did; the key is `subjectDid`.

The equivalent call with the node fetch API would look like this:

```
const did = {subjectDid: "did:example:123"};

const response = await fetch('https://sign-and-verify.herokuapp.com/verify/credentials', {
  method: 'POST',
  body: JSON.stringify(did),
  headers: {
    'Content-Type': 'application/json',
    Accept: "application/json"
  }
});
```

## Out of scope
- Authentication
- Nonce, 1-time tokens, etc
- Out-of-band credential request (for now)
- Credential manifest / other standards
- QR deep link into the app. This is tracked with #41 

## Related 
This issue focuses on scanning a QR code to request a credential. QR scanning might also be used to import an already-issued credential into the wallet (perhaps with warnings if wallet is not aware of the subjectDid in the credential.

**Comment by kimdhamilton** [comment]
Rough attempt to get QR scan working here: https://github.com/digitalcredentials/cred-wallet/pull/51

**Comment by jchartrand** [comment]
Two questions:

1. Step 3 of the Flow described above says "Scan QR code".

Where is that QR code?  In an email invitation sent to the student and/or on a web page on the issuer's web site?

2.  It might have been Stuart who suggested that (most/all?) new iOS/android versions will now automatically recognize a QR code, and will read and open the encoded link.   Could we just piggyback on that and have the QR code open to our demo site on a page that will then redirect the user's browser to automagically open the app or prompt the user to install the app? Or does the automagic opening  only work if we register our app in the iOS/android store?

I did find this npm package for incorporating a QR reader into react-native, although I don't know how stable it is:

https://www.npmjs.com/package/react-native-qrcode-scanner

I'm happy to look into this more.

**Comment by kimdhamilton** [comment]
1. For now, assume it's on the issuer's web site (we can add other cases later). 

Getting started, the DCC playground can serve as our issuer web site -- the "request" page has a QR code placeholder we can use. Note that the QR code that currently shows is just a placeholder (it encodes the wikipedia url) so there is a corresponding dual issue to generate the QR code there https://github.com/digitalcredentials/docs/issues/38. 

Even though that issue is a "prerequisite", I still think there's work that can be done on this side to prepare for a correct QR code. I started trying to get QR code scanning working in this PR (https://github.com/digitalcredentials/cred-wallet/pull/51) but I was getting errors. I may have used that package (I can't remember)

2. Absolutely, I'd like to piggyback if possible. I believe that the trick is registering an app path/prefix when the app is installed, but hopefully there's a way for us to experiment with this outside the app store (i.e. in some test mode). Investigating this would be a great help.

*Unrelated build topic*
If this is your first time playing with this repo in a while, note that I updated a lot of package dependencies in the process of getting a more reliable/consistent build. I recommend nuking previous build files and app state to avoid unnecessary trauma.

The biggest change was in the react native 0.63 upgrade, which enables dynamic pod config. [This change](https://github.com/digitalcredentials/cred-wallet/commit/6d4a3dc13841447ca467dac2e1b4c08bd4cdd33d#diff-2505890afb91c875be64ad195a1502a6) alone seemed to fix most of the ongoing problems.

Let me know if you have any issues.

**Comment by jchartrand** [comment]
I spent a bit of time yesterday on how deep linking works in react (both in production and during development)- getting there I think.

A question though:  why do we need QR codes, rather than just normal clickable links?  

Won't a person always be able to open the same web page (the one that shows the QR code) in a web browser on their phone, and so could just click the link from there?  Or if the QR is in an email, they could similarly just open the email on their phone and click the link?

**Comment by jchartrand** [comment]
I guess what I'm saying is that there could be a different flow.  So instead of the flow described above:

- User opens DCC wallet
- Navigates to "Request Credential" screen
- Scan QR code (from web page on issuer's site)
- Next screen displays:
a)The scanned info. For now, that's just the URL for the "request credential" REST service. Later it might contain other info such as a challenge/nonce
b)A DID auto-populated from the wallet. For now, just make it did:example:123 or something.
- User hits "submit" button which hits the rest endpoint and returns a signed mock credential

It would instead go:

* User opens the 'credential request' web page on an issuer's site, from the web browser on their phone.
* User clicks a link on the issuer's web page to 'Request Credential'
* Link opens DCC wallet on user's phone and passes in (as request params on the url) whatever wallet needs, in particular the url that the wallet should send the request for credential
* wallet makes the call, sending DID, token, whatever.

I guess this is effectively more like how Blockcerts works.

**Comment by kimdhamilton** [comment]
Updates per 8/28 call. Additional details in #37 

- The QR code generated by the issuer will contain a DID Auth challenge like [example 3 in the VP request spec](https://w3c-ccg.github.io/vp-request-spec/#example-3-a-didauth-request). 
- The learner needs to scan the QR code and send the response (example 4 in the VP request spec). I guess this means the QR code has to encode
   - arguments about the issuer endpoint
   - challenge the wallet needs to sign
   - (if piggybacking on ios/android QR scan) instructions about which app to open (namespace, etc)

@dmitrizagidulin @jchartrand:
- does this sound correct?
- perhaps we should track a separate issue for "implement did auth in app" and then this issue can just worry about the basic QR flow (i.e. ensuring the QR scan gets to the right location in the wallet, and then simply calls the current method. Then we update after we have did auth implemented.

Note, by "current method" I mean the simple api described in detail above
```
curl --header "Content-Type: application/json" --request POST --data '{"subjectDid": "did:example:123"}' https://sign-and-verify.herokuapp.com/request/credentials
```

**Comment by kimdhamilton** [comment]
On further thought, let's definitely scope this issue to the current dummy "request" method described at the top. I'll create a separate issue to track DID auth as a subsequent addition. I think DID auth would increase the scope of this issue a lot.

**Comment by jchartrand** [comment]
I'll take a crack at this.

**Comment by jchartrand** [comment]
@kimdhamilton 

I've got the QR scan working, and am now setting up the call to retrieve the credential from the url encoded into the QR code.

I was pretty sure I remembered seeing the QR code on the DCC playground in the QR tab of:

https://digitalcredentials.github.io/playground/

but now I don't see the QR code.  Is it somewhere else?

For now, I can hard-code the api call into the app (which might be what you wanted anyhow).

**Comment by kimdhamilton** [comment]
Sorry, it's in the "request" page (left hand navigator, bottom selection) For some reason, direct sublinks on the playground don't work -- i.e. I don't know why this direct link doesn't work: [](https://digitalcredentials.github.io/playground/request)

**Comment by kimdhamilton** [comment]
Oh, but a hardcoded call is good for now, because the QR code there is a dummy one (wikipedia). There's another issue in the docs repo to track creating the correct QR code.

**Comment by kimdhamilton** [comment]
The latest version of the credential request ceremony is here: https://github.com/digitalcredentials/docs/blob/master/request/credential_request.md
