### ISSUE TITLE
Home Screen: Suppress display of Mortar Board (graduation cap)

### ISSUE THREAD

**Issue by kimdhamilton** [digitalcredentials/cred-wallet#73]
For initial release, we don’t foresee more than non-academic issuers.

In current design, mortar board can lead to confusion (what information is it trying to convey, what does the color mean, etc.). Suppress display for now.

From MIT [UX Wallet Review](https://docs.google.com/document/d/1X4SIchGr0titkV7sGhT4mWwzCq3uvYf_KdtJiCk8Ecg/edit)

**Comment by dirkcuys** [comment]
![Screenshot_1622469949](https://user-images.githubusercontent.com/121995/120205461-452e2880-c22a-11eb-9441-741ab148e597.png)

Is this mortar board being referred to, defined [here](https://github.com/digitalcredentials/cred-wallet/blob/master/app/components/CredentialsList/index.tsx#L43-L50)? I don't see any other references to any of the graduation cap images, so I went ahead and removed that.

**Comment by kimdhamilton** [comment]
yes, that's the one. it's the place I saw mortar boards too, so you're all good

**Comment by kimdhamilton** [comment]
fix confirmed
